# Generated by Django 4.1.2 on 2023-01-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_match_away_team_alter_match_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invite_code',
            field=models.CharField(default='123456', max_length=10),
            preserve_default=False,
        ),
    ]
