# Generated by Django 4.1.2 on 2023-01-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_team_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
