# Generated by Django 4.1.2 on 2023-01-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_matchstatistic_tackles_made_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('prop', 'Prop'), ('hooker', 'Hooker'), ('lock', 'Lock'), ('flanker', 'Flanker'), ('no8', 'No. 8'), ('scrum_half', 'Scrum Half'), ('fly_half', 'Fly Half'), ('centre', 'Centre'), ('wing', 'Wing'), ('full_back', 'Full Back')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ManyToManyField(to='stats.position'),
        ),
    ]
