# Generated by Django 4.1.2 on 2023-01-26 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_position_remove_player_position_player_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchStatistic',
            new_name='PlayerStatistic',
        ),
    ]
