# Generated by Django 4.1.2 on 2023-01-31 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_match_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tries_scored', models.IntegerField(default=0)),
                ('tries_conceded', models.IntegerField(default=0)),
                ('scrums_won', models.IntegerField(default=0)),
                ('scrums_lost', models.IntegerField(default=0)),
                ('lineouts_won', models.IntegerField(default=0)),
                ('lineouts_lost', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_statistics', to='stats.match')),
                ('motm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.team')),
            ],
        ),
    ]
